let car=`sonata`
console.log("if car==`sonata` ? u predict true");
console.log(car==`sonata`)

let bike=`honda`
console.log("if bike==`honda`?u print true");
console.log(bike==`honda`);

let cycle=`sohrab`
console.log("if cycle==`sohrab`?u print true");
console.log(cycle==`sohrab`);



let aeroplane=`pia`
console.log("if aeroplane==`pia`?u print true");
console.log(aeroplane==`pia`);



let aeroplanes=`pia`
console.log("if aeroplanes===`pia`?u print true");
console.log(aeroplanes==`pia`);



let home=`bahriatown`
console.log("if home==`bahriatown`?u print true");
console.log(home==`bahriatown`);

let cars=`gli`
console.log("if cars==`sonata` ? u predict true");
console.log(cars==`sonata`)



let homes=`parkview city`
console.log("if homes==`bahriatown`?u print true");
console.log(homes==`bahriatown`);

let cycles=`phoenix`
console.log("if cycles==`sohrab`?u print true");
console.log(cycles==`sohrab`);

let bikes=`yamaha`
console.log("if bike==`honda`?u print true");
console.log(bikes==`honda`);
