var car = "sonata";
console.log("if car==`sonata` ? u predict true");
console.log(car == "sonata");
var bike = "honda";
console.log("if bike==`honda`?u print true");
console.log(bike == "honda");
var cycle = "sohrab";
console.log("if cycle==`sohrab`?u print true");
console.log(cycle == "sohrab");
var aeroplane = "pia";
console.log("if aeroplane==`pia`?u print true");
console.log(aeroplane == "pia");
var aeroplanes = "pia";
console.log("if aeroplanes===`pia`?u print true");
console.log(aeroplanes == "pia");
var home = "bahriatown";
console.log("if home==`bahriatown`?u print true");
console.log(home == "bahriatown");
var cars = "gli";
console.log("if cars==`sonata` ? u predict true");
console.log(cars == "sonata");
var homes = "parkview city";
console.log("if homes==`bahriatown`?u print true");
console.log(homes == "bahriatown");
var cycles = "phoenix";
console.log("if cycles==`sohrab`?u print true");
console.log(cycles == "sohrab");
var bikes = "yamaha";
console.log("if bike==`honda`?u print true");
console.log(bikes == "honda");
