var a = "hasnat";
var b = "waleed";
var c = a === b;
console.log(c);
var n = "yamaha bike";
var m = "yamaha bike";
var g = m == n;
console.log(g);
var q = "HASNAT JAMIL";
var w = "hasnat jamil";
var r = q.toLocaleLowerCase() === w;
console.log(r);
console.log(q != w);
var p = 12;
var z = 22;
console.log(p === z);
console.log(p !== z);
console.log(p > z);
console.log(p < z);
;
var j = 13;
var k = 12;
console.log(j === k);
console.log(k > j || k < j);
console.log(j > k || j < k);
console.log(k < j);
console.log(k > j && k < j);
var arr = ["ahsan", "waleed", "hasnat", "osama"];
console.log(arr.includes("yaseen"));
