"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.nameofpersons = void 0;
var nameofpersons = ["hasnat", "awais", "Ahsan", "Waleed"];
exports.nameofpersons = nameofpersons;
console.log("hi", nameofpersons[0], "tomorrow i will invite u in late night dinner");
console.log("hi", nameofpersons[1], "tomorrow i will invite u in late night dinner");
console.log("hi", nameofpersons[2], "tomorrow i will invite u in late night dinner");
console.log("hi", nameofpersons[3], "tomorrow i will invite u in late night dinner");
console.log("sorry", nameofpersons[2], "cant make the dinner");
nameofpersons.splice(2, 1, "hamza ali");
console.log("hi", nameofpersons[0], "tomorrow i will invite u in late night dinner");
console.log("hi", nameofpersons[1], "tomorrow i will invite u in late night dinner");
console.log("hi", nameofpersons[2], "tomorrow i will invite u in late night dinner");
console.log("hi", nameofpersons[3], "tomorrow i will invite u in late night dinner");
