let alien_colour="green"
if(alien_colour=="green")
{console.log(" player just earned 5 points for shooting the alien.");
} else{
    console.log( "player just earned 10 points for shooting the alien.");
    
    
}
alien_colour="yellow"
if(alien_colour=="green")
{console.log(" player just earned 5 points for shooting the alien.");
} else{
    console.log( "player just earned 10 points for shooting the alien.");
    
    
}